### ISSUE TITLE
Fix mobile CSS

### ISSUE THREAD

**Issue by srush** [ICLR/iclr.github.io#12]
Check mobile for all pages / integrate better with bootstrap CSS.

**Comment by yassersouri** [comment]
I can work on this.

**Comment by srush** [comment]
great, I think the sponsors page is particularly bad

**Comment by yassersouri** [comment]
I tried to look at most of the pages in mobile view and they seemed okay. I have already created 2 pull requests.

If there is anything that you find problematic in mobile let me know. Otherwise I would suggest the we close this issue :)
