### ISSUE TITLE
Add a chat room for Help on the FAQ page. 

### ISSUE THREAD

**Issue by srush** [ICLR/iclr.github.io#19]

**Comment by srush** [comment]
https://iclr.rocket.chat/channel/tech-support

You can use the same embed code as on one of the Papers pages.

**Comment by jaketae** [comment]
Hi, a volunteer for ICLR here. I'd like to take a jab at this issue, but I'm not entirely sure if I understood what you mean by "embed code as on one of the Papers pages." I was considering adding a block of text directly in `sitedata/faq.yml`. Is this acceptable or something you had in mind? Thank you.

**Comment by srush** [comment]
no, I actually want the chat room embedded there. Look at the other pages for examples of embedding chat.

**Comment by jaketae** [comment]
Got it. Is there a specific layout you have in mind? At the moment, I just have a chat window embedded into the page as shown.
<img width="1440" alt="Screen Shot 2020-04-11 at 7 48 42 AM" src="https://user-images.githubusercontent.com/25360440/79027947-1f2e6a80-7bc9-11ea-9c9a-0e0d8d570cce.png">

**Comment by srush** [comment]
Great for now!
