### ISSUE TITLE
Implement a "Papers" page for each of the workshops

### ISSUE THREAD

**Issue by srush** [ICLR/iclr.github.io#27]

**Comment by soumya-ch** [comment]
Do we have the list of workshop papers in the site date?
The workshop descriptions also need to be filled in.

**Comment by srush** [comment]
Yeah, we are getting all this information. But you can create some fake
data to start the page.

**Comment by soumya-ch** [comment]
For the list of papers, should I use the format of `papers.json` or a simple yml file?
Should the page be like `papers.html` or a simple listing of papers like the following?

![image](https://user-images.githubusercontent.com/33203398/79013684-e66da180-7b86-11ea-8258-c4435422a471.png)

**Comment by srush** [comment]
I don't care how you do the backend, yml is probably easiest for now..

For the front-end it should look like papers.html (except no picture) and
then a poster_.html with no "similar papers".
