### ISSUE TITLE
ICS files interpretable as local time?

### ISSUE THREAD

**Issue by sjmielke** [ICLR/iclr.github.io#64]
The generation of ICS events with `icalendar`
https://github.com/ICLR/iclr.github.io/blob/2abb630a7960d2a9e35db11cf26e99ca2bf93917/main.py#L295
produces events that use GMT, indicating so in the timezone attribute, too, but Thunderbird and iOS both interpret the time as local time, presumably because the final `Z` is missing after the datetimes? That is, `DTSTART;VALUE=DATE-TIME:20200430T120000` is delivered, but appending a `Z` makes it work for me.

I'm not sure why `icalendar` doesn't do that for `dtstart` and `dtend`, but does it for `dtstamp`, and maybe there's a good reason for it. If all else failed, one could hackily append the `Z`, but I'm sure there's a principled thing to do...

**Comment by srush** [comment]
Amazing find. I had no Idea. I will fix.

**Comment by srush** [comment]
Push a fixed. Let me know if it works for you now.

**Comment by sjmielke** [comment]
Like a charm! (And reassuring that no hackery was needed...) Thanks for the quick fix :)
