### ISSUE TITLE
Error in loading the pretrained model

### ISSUE THREAD

**Issue by AnirudhDagar** [ICLR/iclr.github.io#74]
Hi @srush Amazing work with ICLR2020. I enjoyed the conference a lot. :)

I was looking into the visualizations and the code for generating the embeddings using the paper abstracts. I am unable to load the pre-trained model you shared [here](https://github.com/ICLR/iclr.github.io/blob/master/recommendations/scratch/similarity-model.pt) When I try to run the cache_paper_embeddings.py file, I face the following error:

```
Loading model
Traceback (most recent call last):
  File "cache_paper_embeddings.py", line 31, in <module>
    model, epoch = load_model(None, "scratch/similarity-model.pt")
  File "/Users/gollum/Desktop/Work/iclr.github.io/recommendations/models.py", line 20, in load_model
    model = torch.load(load_file, map_location=lambda storage, loc: storage)
  File "/Users/gollum/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/gollum/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```  

This is imo problem with the saved model keys. If possible can you share steps to run the code for training this model? 

Thanks!

**Comment by srush** [comment]
Hi,

You will need to use and install `git lfs` to clone the model. You also
will need to run it on GPU (like collab).

Here are the commands I ran (maybe you can add a README file?)

!apt-get install git-lfs
!git lfs install
!rm -fr iclr.github.io
!git clone https://github.com/ICLR/iclr.github.io
!pip install -r iclr.github.io/requirements.txt
!pip install -r iclr.github.io/recommendations/requirements.txt

**Comment by AnirudhDagar** [comment]
I did actually use git lfs earlier. But somehow the model was still not unpickling even with a GPU enabled machine.

I repeated the whole process now just to be double sure. It works as expected. Probably something went wrong earlier.

Thanks! I'll make a PR for the readme and mention the steps explicitly.

**Comment by srush** [comment]
Yeah, the error you gave was what happens when lfs fails.
